version: '3'
services: 
  server:
    image: doucker/uber-api:latest
    environment:
      dbhost: db
    container_name: uber-api
    links: 
      - db
    depends_on:
      - db
    ports: 
      - "3000:3000"

  db:
    image: "mdillon/postgis:9.6"
    container_name: uber-db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: alliswell
      
    ports: 
      - "5438:5432"
    volumes: 
      - uber-db-data:/var/lib/postgresql/data #persistence
volumes: 
  uber-db-data: {}