name: hello_angel
description: A starting point for Dart libraries or applications.
# version: 1.0.0
# homepage: https://www.example.com
# author: bettdalpha <bettdalpha@gmail.com>

environment:
  sdk: '>=2.4.0 <3.0.0'

dependencies:
 path: ^1.6.0
 angel_framework: ^2.0.0
 angel_hot: ^2.0.0
 postgres: any
 latlong: any
 csv: any

dev_dependencies:
  pedantic: ^1.8.0
  test: ^1.6.0
